### ISSUE TITLE
Message handling infinite loop problem

### ISSUE THREAD

**Issue by aooppo** [golevelup/nestjs#112] opened 2020-03-24 09:55 UTC
Hi, I created a new subscription according to the following document, and then after I return **new Nack()**, I still receive the previous message indefinitely. Is this the problem I set?

**dependencies:**

- "@nestjs-plus/rabbitmq": "^1.4.4",    
-  "@nestjs/common": "^6.0.0",     
- "@nestjs/core": "^6.0.0",

> Message Handling
> NestJS Plus provides sane defaults for message handling with automatic acking of messages that have been successfully processed by either RPC or PubSub handlers. However, there are situtations where an application may want to Negatively Acknowledge (or Nack) a message. To support this, the library exposes the Nack object which when returned from a handler allows a developer to control the message handling behavior. Simply return a Nack instance to negatively acknowledge the message.
> 
> By default, messages that are Nacked will not be requeued. However, if you would like to requeue the message so that another handler has an opportunity to process it use the optional requeue constructor argument set to true.

```
import { RabbitRPC } from '@golevelup/nestjs-rabbitmq';
import { Injectable } from '@nestjs/common';

@Injectable()
export class MessagingService {
  @RabbitRPC({
    exchange: 'exchange1',
    routingKey: 'rpc-route',
    queue: 'rpc-queue'
  })
  public async rpcHandler(msg: {}) {
    return {
      if (someCondition) {
        return 42;
      } else if (requeueCondition) {
        return new Nack(true);
      } else {
        // Will not be requeued
        return new Nack();
      }
    };
  }
}
```

my code:
```
import { RabbitMQModule } from '@nestjs-plus/rabbitmq';
import { Module } from '@nestjs/common';
import { MessagingService } from './messaging.service';
import { MessagingController } from './messaging.controller';
import MSG from './msg.constant';

@Module({
  imports: [
    RabbitMQModule.forRoot({
      exchanges: [
        {
          name: 'emailExchange',
          type: 'topic',
        }
      ],
      uri: 'amqp://root:123456@localhost:5672',
    }),
  ],
  providers: [MessagingService],
  controllers: [MessagingController],
})
export class MessagingModule {}
```
```
import { Injectable } from '@nestjs/common';
import { RabbitSubscribe, Nack, RabbitRPC } from '@nestjs-plus/rabbitmq';
@Injectable()
export class MessagingService {
  @RabbitSubscribe( {
      exchange: 'emailExchange',
      routingKey: 'emailRouting',
      queue: 'emailQueue',
  }  )
  public async subscribeHandler(payload: {}) {
    console.log(`Subscribe Received message: ${JSON.stringify(payload)}`);
    return new Nack();
  }
}
```

**Comment by zerobig** [comment] 2020-03-25 06:54
Hello, @nestjs-plus/rabbitmq is very old version of the library. Try use @golevelup/nestjs-rabbitmq v.1.10.0. If the problem persists, then I will see into.

**Comment by aooppo** [comment] 2020-03-25 07:59
Thanks for your reply @zerobig 
I upgrade some package for dependencies, but it still doesn't work. do you have any idea?

    "@golevelup/nestjs-rabbitmq": "^1.10.0",
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",

**Comment by sjmittal** [comment] 2020-04-21 08:44
This does not work for me too.
I think it has something to do with this line of code:
https://github.com/golevelup/nestjs/blob/master/packages/rabbitmq/src/amqp/connection.ts#L264

It always returns false.

**Comment by WonderPanda** [comment] 2020-04-21 13:05
Hey @sjmittal I'm sorry that you're seeing this behavior. If you're for sure returning a `Nack` instance from your handler this should be working as intended. 

We have integration test coverage against a real RabbitMQ for the Nack behavior here:
https://github.com/golevelup/nestjs/blob/master/integration/rabbitmq/e2e/nack-and-requeue.e2e-spec.ts

I'm wondering if somehow the instanceof check is failing because of versioning issues still present? Is there any way you can reproduce this in a sample app so that I can take a better look at it?

**Comment by sjmittal** [comment] 2020-04-21 14:22
@WonderPanda 
Issue is indeed very weird.
If I run the test case you mentioned exactly in my test suite it passes. So there is no versioning issue.

Now I did bit debugging using console logs at library level; nack response in test case is logged as:
`Nack { _requeue: false }`

However in my code to check this further I did:
```
    const x = new Nack();
    console.log(x);
    return x;
```

I also added a log in the lib itself where message is getting handled.
The logs were something like:
```
Nack { _requeue: false }
{ _requeue: false }
```

So somehow by the time the message is reached to the library layer the `Nack` type is getting erased. But same is not happening in the test case.
Not sure why, this needs further debugging.

**Comment by WonderPanda** [comment] 2020-04-21 16:21
@sjmittal Thanks for following up. It looks like there is definitely some kind of bug or edge case where your message is being serialized such that the reference to the parent Nack constructor is being erased. I will look into this more tonight

**Comment by WonderPanda** [comment] 2020-04-21 16:22
@sjmittal Thanks for following up. It looks like there is definitely some kind of bug or edge case where your message is being serialized such that the reference to the parent Nack constructor is being erased. I will look into this more tonight

**Comment by sjmittal** [comment] 2020-04-22 05:46
So after some debugging I have found out the issue why it is failing at app level whereas test cases are passing correctly.
In nestjs for obvious reason (as described in link: https://docs.nestjs.com/techniques/serialization) we use https://github.com/nestjs/nest/blob/master/packages/common/serializer/class-serializer.interceptor.ts
So in this line it converts all classes to plain before putting the `Nack` object on network:
https://github.com/nestjs/nest/blob/master/packages/common/serializer/class-serializer.interceptor.ts#L62

Hence on the amqp library side we always get an plain object. I guess you may need a different way to check for `Nack` objects.
Or perhaps if you can suggest a better way to use class serialization. The golevelup rabbitmq is just module of a bigger nest application, so I suppose we just cannot do away with serialization.

**Comment by WonderPanda** [comment] 2020-04-22 11:15
@sjmittal Can you share how you're configuring the Interceptor? I think there is a little bit of confusion in regards to the serialization piece here.

It's important to understand that the `Nack` is not being sent over the network. The way that the RabbitMQ library works is that messages are received and automatically routed to your handlers based on decorators but when your handler method returns a value that value is processed in the running process. The comparison for `Nack` happens immediately before any response is sent through RabbitMQ.

Do you have a global interceptor turned on? It doesn't make sense to have one set up that's also intercepting calls on internal services that aren't participating in network communication

**Comment by sjmittal** [comment] 2020-04-23 11:02
@WonderPanda 
I am using a global interceptor here, but then as per https://docs.nestjs.com/techniques/serialization, this should kick in only before objects are returned in a network response.
As you say that Nack is not being sent over network then why is it being serialized? Is that some bug in `NestJS` side.
Apart from global interceptor I am doing having any additional configuration.

Does it make sense to not allow `Nack` to be serialized at all using some annotations?

**Comment by WonderPanda** [comment] 2020-04-23 12:06
@sjmittal The link you've provided is a bit misleading. Interceptors are often used in conjunction with transforming responses to be sent over the network as one of the primary use cases for NestJS is building REST APIs. However, Interceptors make no distinction in behavior based on whether they're being used at a network boundary or not.

They simply grab the result produced by the method they are "intercepting" and then do something to that payload. There's no reason to be applying a serialization interceptor globally on all your services. You are actually incurring a performance penalty at the moment because all your messages from Nest Providers need to be processed an additional time. It would be much better for you to configure your serialization interceptor on all of your Controllers so it handles outbound API traffic instead of all internal.

I'm going to close this as it's not a problem with this library and can be fixed with proper use of Interceptors. However, I have some thoughts about possibly making the Nack check more intelligent so I may add something to the library regardless depending on my availability. If I improve the Nack check in the future I'll update you in this thread

**Closed as completed by WonderPanda** 2020-04-23 12:06 UTC

**Comment by chromey** [comment] 2022-02-18 16:42
Hi @WonderPanda 

I just stumbled over this exact problem. Do you still stand by your assessment that using the `ClassSerializerInterceptor` globally is discouraged? In particular, you mention that global interceptors are applied to *all* Nest providers, but the Nest docs state that this only true for "every controller and every route handler", and that's also my experience - which would mean they in fact only act at network boundaries.

So in light of this, would you reconsider updating the Nack check?
