### ISSUE TITLE
Please make sure that the argument Symbol(GraphQLClientInject) at index [0] is available in the <Module> context

### ISSUE THREAD

**Issue by raviada4440** [golevelup/nestjs#395] opened 2022-02-14 12:42 UTC
"@nestjs/common": "^8.2.6",
      "@nestjs/config": "^1.1.6",
      "@nestjs/core": "^8.2.6",
      "@nestjs/graphql": "^10.0.2",
      "@nestjs/jwt": "^8.0.0",
      "@nestjs/mapped-types": "*",
      "@nestjs/passport": "^8.1.0",

`app.module.ts`

      imports: [
        GraphQLRequestModule.forRoot(GraphQLRequestModule, {
          // Exposes configuration options based on the graphql-request package
          endpoint: "http://localhost:1337/graphql",
          options: {
            headers: {
              'content-type': 'application/json',
            },
          }
        }),
       LocationsModule,
     ],

`locations.service.ts`

    constructor(@InjectGraphQLClient() private readonly client: GraphQLClient) { }

`locations.module.ts

    providers: [LocationsService]

Getting this error when starting nestjs

    [Nest] 60738  - 02/14/2022, 6:20:25 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the LocationsService (?). Please make sure that the argument Symbol(GraphQLClientInject) at index [0] is available in the LocationsModule context.
    
    Potential solutions:
    - If Symbol(GraphQLClientInject) is a provider, is it part of the current LocationsModule?
    - If Symbol(GraphQLClientInject) is exported from a separate @Module, is that module imported within LocationsModule?
      @Module({
        imports: [ /* the Module containing Symbol(GraphQLClientInject) */ ]
      })

How to import GraphQLRequestModule once in app.module and inject in all services? It doesn't make sense to import `GraphQLRequestModule` in every module, am I missing something? please help.

thanks in advance.

**Comment by rmendoza-prescriber** [comment] 2022-02-23 01:44
Good evening folks! I have the same issue as @raviada4440, any luck on this?

**Comment by underfisk** [comment] 2022-03-08 13:39
@raviada4440 Can you make sure you only have 1 nestjs package installed, what i've noticed after upgrading to v8 is the conflicts with the dependency injection when multiple versions are installed, if that doesn't solve this particular issue, could you create a github repro so that we can investigate?

**Comment by WonderPanda** [comment] 2022-05-31 11:56
@raviada4440 It looks like you're importing the GraphQLRequestModule inside of your `AppModule` but then trying to consume its providers inside of `LocationsModule`.

Try moving the import of GraphQLRequestModule into LocationModule. This library does not provide a Global so you won't be able to import across modules like that.

I'm going to close this for now since there is not a clear reproduction provided. @raviada4440 or @rmendoza-prescriber Feel free to open it again if you can include a minimal reproduction demonstrating your issue

**Closed as completed** 2022-05-31 11:58 UTC

**Comment by smnbbrv** [comment] 2023-03-24 12:09
The name `GraphQLRequestModule.forRoot` is unbelievably confusing. The forRoot indicates to put it in the project ROOT and not in the CHILD module.
