### ISSUE TITLE
ts-jest - When function is called with a mock, toHaveBeenCalledWith() always succeed even when it should not

### ISSUE THREAD

**Issue by maxime-dupuis** [golevelup/nestjs#703] opened 2024-02-27 14:56 UTC
```
it('mock called with another mock', async () => {
  class Cheese {
    constructor(public name: string) {}
  }
  class Potato {
    private cheese: Cheese;
    public applyCheese(cheese: Cheese) {
      this.cheese = cheese;
    }
  }
  const mockPotato = createMock<Potato>();
  const mockCheese = createMock<Cheese>();

  mockPotato.applyCheese(mockCheese);

  expect(mockPotato.applyCheese).toHaveBeenCalledTimes(1);
  // These all pass, but they should fail because applyCheese wasn't called with these values
  expect(mockPotato.applyCheese).toHaveBeenCalledWith('kaboom');
  expect(mockPotato.applyCheese).toHaveBeenCalledWith(42);
  expect(mockPotato.applyCheese).toHaveBeenCalledWith(null);
  // This one should pass (and does)
  expect(mockPotato.applyCheese).toHaveBeenCalledWith(mockCheese);
});
```

**Comment by VonRehberg** [comment] 2024-06-27 08:53
Experiencing the same issue. Is there something we can do about it?

**Comment by VonRehberg** [comment] 2024-08-09 12:42
Hey @underfisk , any plans on when the package will be updated?
The issue is fixed with the merge request #752 
Thanks in advance!

**Comment by underfisk** [comment] 2024-08-09 16:08
> Hey @underfisk , any plans on when the package will be updated?
> 
> The issue is fixed with the merge request #752 
> 
> Thanks in advance!

Only @WonderPanda can publish

**Comment by WonderPanda** [comment] 2024-08-09 17:37
Just published. This should be available in @golevelup/ts-jest@0.5.1

**Comment by VonRehberg** [comment] 2024-08-09 20:19
Thanks a lot man!

**Closed as completed** 2024-09-26 13:08 UTC
Labels: testing
