### ISSUE TITLE
PubSub consumer never consumes messages with RabbitSubscribe

### ISSUE THREAD

**Issue by LucSalommez** [golevelup/nestjs#273] opened 2021-06-01 11:36 UTC
Hello,

I have an issue with consuming messages in a pubsub maner.
I am able to create a connection to the exchange and to publish messages on it (confirmed on the UI).

I do not understand why my function associated with RabbitSubscribe is never called.
I have triple checked the exchange and route key and it is correct.

In my Module I use :
```
		RabbitMQModule.forRoot(RabbitMQModule, {
			exchanges: [
			  {
				name: 'exchange1',
				type: 'fanout',
			  },
			],
			uri: 'amqp://localhost:5672',
			connectionInitOptions: { wait: false },
		  }),
```

And my service :
```
import { Injectable } from "@nestjs/common"
import { AmqpConnection, RabbitSubscribe } from "@golevelup/nestjs-rabbitmq"

@Injectable()
export class MailService {
	constructor(private readonly amqpConnection: AmqpConnection) {
		// setTimeout(function() {
		// 	console.log("inside")

		// 	amqpConnection.publish("exchange1", "subscribe-route", { msg: "hello world" })
		// }, 3000)
	}

	@RabbitSubscribe({
		exchange: "exchange1",
		routingKey: "subscribe-route",
		queue: "subscribe-queue",
	})
	public async pubSubHandler(msg: {}) {
		console.log(`Received message: ${JSON.stringify(msg)}`)
	}
}
```

Is there something I am missing ?
Thanks

**Comment by WonderPanda** [comment] 2021-06-01 13:19
Please share the start up logs from your Application specifically the ones emitted from the RabbitMQ package. These should show the subscribers and patterns being attached

**Comment by LucSalommez** [comment] 2021-06-02 09:02
Hello and thanks for your help @WonderPanda .
I do not find any specific logs from RabbitMQ except for the module being initialized.
Maybe the problem occurs on a registration level ?

Here is the complete log of the startup of my application :
```
[Nest] 84247   - 02/06/2021 à 10:58:17   [NestFactory] Starting Nest application...
[Nest] 84247   - 02/06/2021 à 10:58:17   [AmqpConnection] Trying to connect to a RabbitMQ broker
[Nest] 84247   - 02/06/2021 à 10:58:17   [RabbitMQModule] Successfully connected to RabbitMQ
[Nest] 84247   - 02/06/2021 à 10:58:17   [InstanceLoader] TypeOrmModule dependencies initialized +8ms
[Nest] 84247   - 02/06/2021 à 10:58:17   [InstanceLoader] ClientsModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:17   [InstanceLoader] ClientsModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:17   [InstanceLoader] ClientsModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:17   [InstanceLoader] ClientsModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:17   [InstanceLoader] ClientsModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:17   [InstanceLoader] HttpModule dependencies initialized +2ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] ConfigHostModule dependencies initialized +7ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] WinstonModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] GrpcModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] TerminusModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [InstanceLoader] RabbitMQModule dependencies initialized +2ms
[Nest] 84247   - 02/06/2021 à 10:58:18   [AmqpConnection] Successfully connected to a RabbitMQ broker
[Nest] 84247   - 02/06/2021 à 10:58:18   [AmqpConnection] Successfully connected a RabbitMQ channel
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmCoreModule dependencies initialized +969ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 84247   - 02/06/2021 à 10:58:19   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[NestWinston] Info      02/06/2021 à 10:58:19 [NestMicroservice] Nest microservice successfully started - {}
[NestWinston] Info      02/06/2021 à 10:58:19 [NestMicroservice] Nest microservice successfully started - {}
Microservice connect is listening
```

Or maybe should I add a flag to have more debug logs ?
Thanks

EDIT : I don't know if this is helpful to you but the UI of RabbitMQ tells me that no consumer is being detected.

**Comment by WonderPanda** [comment] 2021-06-02 11:46
There are no logs indicating that the handler has been discovered so I think there is something wrong with your setup. Did you register `MailService` in the `providers` array of its parent module? Only registered providers can be discovered

**Comment by LucSalommez** [comment] 2021-06-02 12:45
The MailService is indeed properly imported in providers.
The constructor of the Service is being called, I can see my `console.log("inside")` and a new message is properly created.

I tried adding a `console.log` in `OnModuleInit()` function of the package and the console.log is never called.
Maybe this is linked to my issue.

I am using the version `"@golevelup/nestjs-rabbitmq": "^1.16.2"` with node version `v14.16.1` and npm version `7.14.0`.

**Comment by WonderPanda** [comment] 2021-06-02 13:00
Is it possible for you to share a minimum reproduction of this issue? It is difficult to diagnose without seeing the problem

**Comment by LucSalommez** [comment] 2021-06-02 14:13
I tried to reproduce the error using a minimalist project and was surprised to see it working.
I thus tried to find what was differing and it seems the issue is coming from my `main.ts` file.

```
import { NestFactory } from "@nestjs/core"

import { AppModule } from "./app.module"
import { MicroserviceOptions } from "@nestjs/microservices"
import { grpcConnectOptions, RabbitmqOptions } from "@starton/interfaces"
import { WINSTON_MODULE_NEST_PROVIDER } from "nest-winston"

async function bootstrap() {
	const app = await NestFactory.create(AppModule)
	app.useLogger(app.get(WINSTON_MODULE_NEST_PROVIDER))
	
	await app.listen(3000); // Using this it works

	// const grpc = await app.connectMicroservice<MicroserviceOptions>(grpcConnectOptions)
	// const rmq = await app.connectMicroservice<MicroserviceOptions>(RabbitmqOptions)
	// await app.startAllMicroservicesAsync()
	
	console.log("Microservice connect is listening")
}

bootstrap()
```

When using the commented version (`app.startAllMicroservicesAsync()`) the subscriber is never registered but when using `app.listen(3000)` it works properly.

Do you know if it possible for it to work with `app.startAllMicroservicesAsync` ?

**Comment by WonderPanda** [comment] 2021-06-02 14:23
@LucSalommez Unfortunately the library isn't a "true" NestJS microservice at the moment so we can't rely on `startAllMicroservicesAsync` to establish listeners at the moment. I'll need to look into this a bit more and see what solutions make sense

Tracking this with #274

**Comment by LucSalommez** [comment] 2021-06-02 14:26
Thank you very much for your help and reactivity.

**Comment by WonderPanda** [comment] 2021-06-02 15:11
No problem. I'm going to close this now as the root cause has been identified and will track any additional info in the dedicated issue for microservices support

**Closed as completed by WonderPanda** 2021-06-02 15:11 UTC

**Comment by kasir-barati** [comment] 2025-05-12 10:26
@WonderPanda, @LucSalommez do we have a working example for pubsub pattern in RabbitMQ with this lib? If yes would you share its link?
