### ISSUE TITLE
Incorrect subscriber handle called

### ISSUE THREAD

**Issue by szlori** [golevelup/nestjs#202] opened 2020-11-13 05:41 UTC
This seems like a bug or a wrong usage on my side, please let me know if you experienced something similar.

We have a topic exchange with different microservices sending events to an audit log service.
In the audit log service we have an `@Injectable()` subscriber class with several `@RabbitSucribe()` handlers, designed to handle different types of events based on `routingKey`.

The routing key is of form "service.action.object" and the handlers' routing key templates are correspondingly, `*.created.*`, `*.updated.*`, `*.deleted.*`, etc. They do very similar things, so I didn't notice at start, but seems even though all data in the message is correctly sent (especially the routing key), the handlers are not consistently called based on the defined template.

For example, an `admin.deleted.User` message might end up being handled by the created or updated handler...

We tried to get to the bottom of this, but can't find anything wrong with our setup or code. Also noticed that if I break up the 1 subscriber class, into several `@Injectable()` classes, each with only 1 `@RabbitSucribe()` handler - the issue goes away.

Is it wrong to use multiple `@RabbitSucribe()` inside one class? Or is there another issue down the line?

EDIT: In fact the separated subscribers with 1 handler also doesn't work (only looked working at start). So what exactly might be the issue?

**Comment by WonderPanda** [comment] 2020-12-07 16:08
@szlori Is it possible for you to share a repo that contains a reproduction of this issue?

**Comment by WonderPanda** [comment] 2020-12-07 16:31
@szlori Also, what is the value for the `queue` that you're setting up in each of the `RabbitSubscribe` decorators? Does each one have it's own unique queue name?

**Comment by WonderPanda** [comment] 2020-12-07 23:53
@szlori I've added additional integration tests that cover your setup and have been unable to reproduce this issue. I suspect that you're reusing the same queue name across multiple `RabbitSubscribe` decorator configuration which will indeed make it possible for different messages to end up at different handlers. In general most applications would want to have a unique queue per subscriber

Please let me know if this helps with your issue or if there's any additional info to go off of. I'll close this in a couple days if I don't hear anything back

**Comment by Sikora00** [comment] 2020-12-10 13:16
I'm facing simillar issue but with rcp.
https://github.com/Sikora00/nodejs-rabbitmq/tree/bug-report

**Comment by WonderPanda** [comment] 2020-12-10 13:50
@Sikora00 You have the same issue that I mentioned in my most recent comment in this thread. You're re-using the same queue name across multiple handlers:

```typescript
@RabbitRPC({
    exchange: 'exchange1',
    routingKey: 'GetSites',
    queue: 'rpc-queue',
  })
  getData() {
    return ['Site1']
  }


  @RabbitRPC({
    exchange: 'exchange1',
    routingKey: 'GetUsers',
    queue: 'rpc-queue',
  })
  getUserData() {
    return ['User1']
  }
```

This is a fundamental part of how RabbitMQ works, if you attach multiple handlers to the same queue then they will all get messages. You should use a unique queue per RPC. RabbitMQ is built to scale to a huge number of queues

**Comment by Sikora00** [comment] 2020-12-10 14:00
@WonderPanda So what is the purpose of using routingKey either?

**Comment by WonderPanda** [comment] 2020-12-10 14:19
@Sikora00 Please review the RabbitMQ patterns documentation around message routing and exchanges. Both of these two links are very valuable in understanding how things work under the hood when it comes to these concepts. Don't worry about the code samples since `@golevelup/nestjs-rabbitmq` abstracts away most of that for you. What is important is that you take a look at the diagrams and concepts being presented so that you understand the relationship between routing, queues and consumers.

Understanding these concepts will make it much easier for you to leverage RabbitMQ across any programming language or library


https://www.rabbitmq.com/tutorials/tutorial-four-javascript.html
https://www.rabbitmq.com/tutorials/tutorial-five-javascript.html

**Comment by WonderPanda** [comment] 2020-12-14 16:58
I'm closing this for now because it works as intended based on the underlying RabbitMQ implementation. If there are additional issues related to this feel free to open or create a new issue

**Closed as completed by WonderPanda** 2020-12-14 16:58 UTC
Labels: waiting for more info
